export const VIBE_EMOJIS: Record<string, string> = {
  "nature-lover": "🌿",
  flirty: "💋",
  "artsy-af": "🎨",
  "academic-weapon": "🏛️",
  "party-animal": "🎉",
  "tech-savvy": "💻",
  "sports-enthusiast": "🏈",
  entrepreneurial: "🚀",
  "creative-soul": "🎭",
  "wellness-focused": "🧘",
  "diverse-community": "🌍",
  foodie: "🍜",
  "career-focused": "📈",
  "inclusive-diverse": "🌈",
  "party-scene": "🥳",
  "city-energy": "🌇",
  "chill-vibes": "🧘",
  "research-driven": "🔬",
  "pre-professional": "💼",
};
